language: node_js
node_js:
  - "11"
after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
notifications:
  email:
    recipients:
      - ramusus@gmail.com
    on_success: change
    on_failure: change
